name: "Build Status Action"

description: "Returns build result"

outputs:
 result:
  description: "Build result"

runs:
  using: "composite"

  steps:
    - name: Set outputs
      run: echo "result=Build Successful" >> $GITHUB_OUTPUT
      shell: bash