name: Java CI pipeline

on:
  push:
   branches:
    - main

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up JDk
      uses: actions/setup-java@v4
      with: 
        distribution: 'temurin'
        java-version: '21'

    - name: Run custom Java action
      uses: ./.github/actions/java-build-with-inputs
      with:
        file-name: CalculatorTest  

    - name: Run custom Java action
      uses: ./.github/actions/java-build-with-inputs
      with:
          file-name: Main
    
    - name: Run Custom Action
      id: custom-action
      uses: ./.github/actions/action-with-output

    - name: Use Output
      run: echo "Result is ${{ steps.custom-action.outputs.result }}"


